### ISSUE TITLE
Issue while using --preserve-provider flag

### ISSUE THREAD

**Issue by anupamgogoi-wso2** [wso2/product-apim-tooling#101]
**Description:**
$ apimcli import-api -k -f dev/A_1.0.0.zip -e qa **--preserve-provider=false**  **--update**

The above command outputs the following error:
`
Existing API found, attempting to update it...
API ID: 13faf93f-554e-45bd-9d7d-a001adceb3bb
Error importing API.
Status: 500 Internal Server Error
Response: Error in adding Swagger definition for the API.
apimcli: Error importing API Reason: 500 Internal Server Error
Exit status 1
`

However, when the **--preserve-provider=false** is omitted it's successful.
So, I believe, when preserve-provider is set to false, provider should be taken from the logged-in user of the target environment

**Comment by harsha89** [comment]
@kasvith We should be able to fix it right?

**Comment by kasvith** [comment]
Can we get the verbose log?

**Comment by kasvith** [comment]
also, contents of the API would help(zipped version)

**Comment by dushaniw** [comment]
This will be fixed with https://github.com/wso2/product-apim-tooling/pull/102

**Comment by dinusha92** [comment]
This has been fixed with the latest #102 PR and the fix is available in v3.0.0-beta APIM CLI distribution. Hence closing the issue. Please reopen the issue if further concerns present.
