### ISSUE TITLE
Error log when deleting an environment using CLI tool

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim-tooling#103]
**Description:**
An error log will be printed on the terminal when deleting an API using the CLI tool. However, the environment will be deleted.
![Screenshot from 2019-09-30 13-51-27](https://user-images.githubusercontent.com/35653110/65866812-1dbaf480-e393-11e9-8b64-8ee70caa6b4c.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Execute `apimcli remove-env --name <ENV_NAME>` command for an existing environment.

**Related Issues:**

**Comment by dinusha92** [comment]
Fixed with #114
