### ISSUE TITLE
Project fails to import when environment is added after project is created.

### ISSUE THREAD

**Issue by nuwand** [wso2/product-apim-tooling#110]
When using the CLI to create and import an API to API Manager, if you add an environment after the project has been initialized (using the init command), the project fails to import to the newly added environment. It complains that the relevant environment does not exist in the api_params.yaml file. The correct behaviour should be that it picks the default values for the API from the api.yaml and swagger.yaml files of the project in case the information cannot be found in the api_params.yaml.

**Comment by dinusha92** [comment]
Fixed with #114
