### ISSUE TITLE
When trying to export an application for a user in the secondary userstore it fails due to "no such file or directory"

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim-tooling#113]
When we login to the apimcli tool with a user in secondary userstore, and then try to export an application of that user, it falis with following error. 

> Executed ImportExportCLI (apimcli) on Tue, 08 Oct 2019 15:03:18 +0530
> [INFO]: Insecure: true
> [INFO]: export-app called
> [INFO]: connecting to https://localhost:8243/token
> [INFO]: ExportApp: URL: https://localhost:9443/api/am/admin/v0.14/export/applications?appName=DefaultApplication&appOwner=TEST.COM/pta88942
> [INFO]: ResponseStatus: 200 OK
> apimcli: Error creating zip archive Reason: open /Users/shehanirathnayake/.wso2apimcli/exported/apps/dev/TEST.COM/pta88942_DefaultApplication.zip: no such file or directory
> Exit status 1

Steps to reproduce:
1. Login to the apimcli tool with user in secondary userstore 
` ./apimcli login dev -u TEST.COM/pta88942 -p 12345 --verbose`

2. try to export application under that user
`./apimcli export-app -n DefaultApplication -o TEST.COM/pta88942 -e dev --insecure --verbose`

According to the workaround the one suspicious point is, in apimcli source in [1] where the archive is created with the appOwner name and with the secondary user store domain is with the format domain/ownername, it searches for a file path with the secondary domain.When we manually created a directory with the name as the secondary domain and  then successfully able to export the zip file. 

[1] [https://github.com/wso2/product-apim tooling/blob/b587982c5951712a3259203b0bd6411774ed24ee/import-export-cli/cmd/exportApp.go#L104](url)

**Comment by uvindra** [comment]
This has been foxed by replacing the "/" character in the application owner name with "#"
