### ISSUE TITLE
APIs should be able to create from openAPI  without wso2 vendor extensions

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim-tooling#124]
**Description:**
Right now we can import APIS to APIM directly from open API only. But for that to work we need at least two vender extensions.

1. x-wso2-basePath -- specify the base path which is the sub context which categorize all the http operation defined in the open API
2. x-wso2-production-endpoints -- specify the actual implementation url of the endpoint.

So we need to use the openAPI attributes like server (in version 3) and combination of attributes host, scheme, base path (in version 2).
Please refer the issue https://github.com/wso2/product-microgateway/issues/847, which explains the solution for the micro gateway

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by malinthaprasan** [comment]
Will be doing this along with https://github.com/wso2/product-apim/issues/7648

**Comment by npamudika** [comment]
Need to fix https://github.com/wso2/product-apim-tooling/issues/271 once this issue is fixed.
