### ISSUE TITLE
The context field of the api.yaml in the created project does not get created properly when using swaggers with x-wso2-basepath

### ISSUE THREAD

**Issue by RameshaKaru** [wso2/product-apim-tooling#128]
**Description:**
The context field of the api.yaml in the created project does not get created properly when using swaggers with x-wso2-basepath

The context in the api.yaml of the project is taken as a combination of the basepath and the version of the given swagger. That context is directly assigned to x-wso2-basepath when importing the project to API Manager.

In the case of the swagger which already has x-wso2-basepath, the context of the api.yaml is taken as a combination of x-wso2-basepath and version. This combined value is assigned to x-wso2-basepath when importing to API Manager, which results in x-wso2-basepath having an additional version part appended.

This results in the following error when invoking the API through the microgateway using OAuth token
{"fault":{"code":900908, "message":"Resource forbidden ", "description":"Resource forbidden . Unclassified Authentication Failure"}}

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
apictl init normal --oas=sampleswagger.json

Use a swagger with x-wso2-basepath as the sampleswagger.json
**Related Issues:**

**Comment by malinthaprasan** [comment]
The implementation changed based on https://github.com/wso2/product-apim-tooling/issues/196
