### ISSUE TITLE
Allow configuring secure endpoint password when moving between environments

### ISSUE THREAD

**Issue by iloshinik** [wso2/product-apim-tooling#143]
**Description:**
With the current implementation, if Secure Endpoint is enabled, the endpoint password is removed when exporting an API causing an error while importing the same API.

This needs to be fixed as,
- If Secure Endpoint is enabled and if the endpoint password should be exposed;
"ExposeEndpointPassword" should be set to "true" in the "/_system/config/apimgt/applicationdata/tenant-conf.json" in the registry so that, the exported API contains the endpoint password. 

- Or else, if Secure Endpoint is enabled and if the endpoint password shouldn't be exposed;
"ExposeEndpointPassword" should be set to "false" in the "/_system/config/apimgt/applicationdata/tenant-conf.json" in the registry. Here, the secure endpoint password is removed while exporting the API, as it causes security issues. Hence, the password needs to be added manually when importing the API.

**Affected Product Version:**
wso2am-2.6.0 
wso2am-3.1.0

**Comment by malinthaprasan** [comment]
This is already fixed by e6168b6471585f163b42f11d865bd99f58fb82d6 (carbon-apimgt).
