### ISSUE TITLE
Soap to rest conversion logs does not get exported when using CLI

### ISSUE THREAD

**Issue by NipunaDilhara** [wso2/product-apim-tooling#145]
**Description:**
 Soap to Rest conversion logic is not exported properly by CLI.

**Suggested Labels:**
apim-cli

**Affected Product Version:**
apim- 2.6.0
cli - 2.0.2

**Steps to reproduce:**
Export an app using CLI which contains a Soap to Rest conversion.

**Comment by npamudika** [comment]
Related to https://github.com/wso2/product-apim/issues/6979 and already fixed via https://github.com/wso2/carbon-apimgt/pull/8006
