### ISSUE TITLE
Error when importing an API by setting the absolute path to the extracted directory.

### ISSUE THREAD

**Issue by NipunaDilhara** [wso2/product-apim-tooling#146]
**Description:**
The following issue is triggered in cli logs when importing an API using an extracted archive file.

Error importing API.
Status: 405 Method Not Allowed
Response:
[INFO]: Deleting C:\Users\ADMINI~1\AppData\Local\Temp\2\api-artifact413510114.zip
[ERROR]: remove C:\Users\ADMINI~1\AppData\Local\Temp\2\api-artifact413510114.zip: The process cannot access the file because it is being used by another process.
[INFO]: Deleting C:\Users\ADMINI~1\AppData\Local\Temp\2\apim559729359/SwaggerPetstore
apimcli: Error importing API Reason: 405 Method Not Allowed
Exit status 1

**Suggested Labels:**
apim-cli

**Affected Product Version:**
apim- 2.6.0
cli - 2.0.2

**Steps to reproduce:**
Export an api using the cli tool
Extract the exported archive file
Then import this api by providing the absolute path to this extracted directory.

**Comment by dushaniw** [comment]
Closing as this is is not reproducible in latest apictl.
