### ISSUE TITLE
APIMCLI export-apis 2.0.2 returns wrong ERRORLEVEL upon export-apis

### ISSUE THREAD

**Issue by sumsum77** [wso2/product-apim-tooling#147]
**Description:**
APIMCLI.exe returns the following ERRORLEVELs:
0 if APIs were exported - this is ok
1 if there was a problem - this is ok
1 if no new APIs were exported - this is not OK!

There should be a difference in ERRORLEVEL between error cases and no new updates.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIMCLI.exe v2.0.2

**OS, DB, other environment details and versions:**    
Windows 10

**Steps to reproduce:**

1. configure and login to environment
1. export all APIs using .\apimcli.exe export-apis -e environment
1. APIs are exported, ERRORLEVEL 0 is returned
1. export all APIs AGAIN using .\apimcli.exe export-apis -e environment
1. as no updates are available nothing is exported, ERRORLEVEL 1 is returned (should be 0, as no error occurred)

**Related Issues:**

**Comment by npamudika** [comment]
Hi, 
Thanks for reporting the issue!
We have fixed the issue and now it returns the ERRORLEVEL 0 as per your suggestion when executing the export-apis command again.

Please find the patch release of the tool at https://github.com/wso2/product-apim-tooling/releases/tag/v2.0.6

**Comment by npamudika** [comment]
This has also been fixed in the latest 3.1.0 version of the tool.
