### ISSUE TITLE
Update documentation(Readme) with relevant information regarding to release version

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim-tooling#176]
**Description:**
This is because recently customer tried out 3.0.1 against APIM-2.6.0 and reported. I believe due to the lack of version compatible information on document is caused for this misunderstanding.
Please update either Readme or APIM-2.6.0 doc with version compatible information.

@Mariangela , please note.

**Comment by npamudika** [comment]
Updated the version related details via https://github.com/wso2/product-apim-tooling/pull/182 for the next release.

**Comment by npamudika** [comment]
The README files of the API-M Tooling repo have been updated accordingly. 

The API-M doc pages will get updated and tracked via https://github.com/wso2/docs-apim/issues/819
