### ISSUE TITLE
apimmcli --update does not push updates to existing documents

### ISSUE THREAD

**Issue by lathlk** [wso2/product-apim-tooling#184]
**Description:**
Changes are not getting reflected in the existing documents when updating an API ("How To" document).

**Affected Product Version:**
APIMCLI 2.0.3

**Steps to reproduce:**

1. Export the API from his tenant which included a document.
2. Make changes in the content.
3. Import with --update into the same tenant.

Changes were not visible even though the command executed successfully.

**Comment by npamudika** [comment]
This has been fixed in the 3.1.0 version with https://github.com/wso2/carbon-apimgt/pull/8240

**Comment by npamudika** [comment]
This is fixed in APIM 2.6.0 version with https://github.com/wso2/product-apim-tooling/releases/tag/v2.0.4
