### ISSUE TITLE
Utility method `IsFileExist` returns true for directory location

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim-tooling#192]
**Description:**
Utility method [`IsFileExist`](https://github.com/wso2/product-apim-tooling/blob/f5f7b44f2944046ea0a40dc830c7dddf9379a682/import-export-cli/utils/fileIOUtils.go#L132) in the file `product-apim-tooling/import-export-cli/utils/fileIOUtils.go` returns true for a valid dir.

tested path: `/Users/renuka/wso2/api-operator/multiple-swagger`

<img width="878" alt="Screenshot 2020-03-16 at 12 44 16" src="https://user-images.githubusercontent.com/23183042/76731645-eb0b8980-6783-11ea-9934-e3adb2bacea4.png">

```sh
renuka@renuka multiple-swagger % ls -ld /Users/renuka/wso2/api-operator/multiple-swagger
drwxr-xr-x@ 4 renuka  staff  128 Mar 16 11:45 /Users/renuka/wso2/api-operator/multiple-swagger
```

```sh
renuka@renuka multiple swagger % tree .
.
├── Screenshot\ 2020-03-16\ at\ 11.39.09.png
└── 2020-03-15.jpg

0 directories, 2 files
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by renuka-fernando** [comment]
Can be update as follows.
```go
// Check whether the file exists.
func IsFileExist(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false
		} else {
			HandleErrorAndExit(fmt.Sprintf(UnableToReadFileMsg, path), err)
		}
	}
	return !info.IsDir()
}
```

Have to check for functionalities that breaks, if it is changed as above.

**Comment by malinthaprasan** [comment]
@renuka-fernando I think it is okay to consider File as File or Directory. If we return false, because the path exists but it is a folder. It might cause confusion. If we need to check if a path is a file or folder, this should be done via a separate method IMO.
