### ISSUE TITLE
API does not created in kubernetes cluster when having empty slice for java interceptors

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim-tooling#198]
**Description:**
When there is no any java interceptors are defined in the project it gives following error while adding API to kubernetes cluster 

Error: 
The API "array" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"wso2.com/v1alpha1", "kind":"API", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"wso2.com/v1alpha1\",\"kind\":\"API\",\"metadata\":{\"annotations\":{},\"creationTimestamp\":null,\"name\":\"array\",\"namespace\":\"default\"},\"spec\":{\"definition\":{\"interceptors\":{\"ballerina\":\"\",\"java\":null},\"swaggerconfigmapName\":\"array-swagger\",\"type\":\"swagger\"},\"mode\":\"privateJet\",\"override\":false,\"replicas\":1,\"updateTimeStamp\":\"\"},\"status\":{}}\n"}, "creationTimestamp":"2020-03-17T11:16:02Z", "generation":1, "name":"array", "namespace":"default", "uid":"afba1128-6840-11ea-abeb-025000000001"}, "spec":map[string]interface {}{"definition":map[string]interface {}{"interceptors":map[string]interface {}{"ballerina":"", "java":interface {}(nil)}, "swaggerconfigmapName":"array-swagger", "type":"swagger"}, "mode":"privateJet", "override":false, "replicas":1, "updateTimeStamp":""}}: validation failure list:
spec.definition.interceptors.java in body must be of type array: "null"
exit status 1

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by npamudika** [comment]
Fixed with above PR.
