### ISSUE TITLE
apimcli 2.1.x is not working - 401 Unable to connect. Reason: Status: 401 Unauthorized

### ISSUE THREAD

**Issue by jpvadell** [wso2/product-apim-tooling#20]
There is an error at 
tokenManagement.go 
Setting the header HeaderAuthorization at func GetOAuthTokens 
Error:
headers[HeaderAuthorization] = HeaderValueAuth**Bearer**Prefix + " " + b64EncodedClientIDClientSecret
And must be:
headers[HeaderAuthorization] = HeaderValueAuth**Basic**Prefix + " " + b64EncodedClientIDClientSecret

Thanks,

**Comment by jpvadell** [comment]
Another thing.
I replaced at func GetOAuthTokens of tokenManagement.go
	body := "grant_type=password&username=" + username + "&password=" + password + "&validity_period=" +
		validityPeriod + "&scope=apim:api_view**+**apim:app_import_export**+**apim:app_owner_change"
To 
	body := "grant_type=password&username=" + username + "&password=" + password + "&validity_period=" +
		validityPeriod + "&scope=apim:api_view apim:app_import_export apim:app_owner_change"

And works great.

**Comment by menuka94** [comment]
>There is an error at
>tokenManagement.go
>Setting the header HeaderAuthorization at func GetOAuthTokens
>Error:
>headers[HeaderAuthorization] = HeaderValueAuthBearerPrefix + " " + b64EncodedClientIDClientSecret
>And must be:
>headers[HeaderAuthorization] = HeaderValueAuthBasicPrefix + " " + b64EncodedClientIDClientSecret

How so?
The `Basic` prefix is dedicated to the authentication using a username and a password [[1]](https://tools.ietf.org/html/rfc7617) and the
`Bearer` prefix is dedicated to the authentication using a token. [[2]](https://tools.ietf.org/html/rfc6750)

[1] https://tools.ietf.org/html/rfc7617
[2] https://tools.ietf.org/html/rfc6750

**Comment by jpvadell** [comment]
Hi Menuka,

At tokenManagement.go the function GetOAuthTokens is used to get the tokens.

So, to get the tokens you need to pass the client_id and client_secret as Basic Authorization. With that you get the token that you use as Bearer Authorization to call the desired API. 

curl -X POST \
  https://localhost:9443/oauth2/token \
  -H 'Authorization: Basic YktvZ1lzOVY0ZEhUdjQ5QjNiU1lQYVBDNHBvYTo4U2VaVlBwczc5MlBYaVdUeXBxUmZhRHF3TEFh' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'grant_type=password&username=admin&password=admin&scope=apim%3Aapi_view%20apim%3Aapp_import_export%20apim%3Aapp_owner_change'

**Comment by jpvadell** [comment]
Another thing.
When try to add a new environment there is a problem, because the variables AppListEndpoint and AdminEndpoint are never filled.

I added this at addEnv.go at addEnv function.

	if envEndpoints.AppListEndpoint != "" {
		validatedEnvEndpoints.AppListEndpoint = envEndpoints.AppListEndpoint
	}

	if envEndpoints.AdminEndpoint != "" {
		validatedEnvEndpoints.AdminEndpoint = envEndpoints.AdminEndpoint
	}

**Comment by npamudika** [comment]
The issue in Authorization header has been fixed in https://github.com/wso2/product-apim-tooling/pull/22
