### ISSUE TITLE
Does not show all the applications in the user's tenant when listing applications

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#205]
**Description:**
When listing applications it only shows user's applications, but not all the applications in the user's tenant. (Refer section **Steps to reproduce** for further understanding )

**Suggested Labels:**
Type/Improvement

**Steps to reproduce:**
- Create an environment as shown below.
  ![image](https://user-images.githubusercontent.com/25246848/77033891-75472e00-69ce-11ea-957a-fcd490952ec9.png)
- Create two users (such as admin1@test.com and admin2@test.com) belong to the same tenant domain.
- Login to devportal using one user (admin1@test.com) and create few (2) applications. 
 ![image](https://user-images.githubusercontent.com/25246848/77034127-32398a80-69cf-11ea-81fc-1708efdab09d.png)
- Similarly, login to devportal using the other user (admin2@test.com) and create few (2) applications. 
  ![image](https://user-images.githubusercontent.com/25246848/77034191-5d23de80-69cf-11ea-8979-4f734b931092.png)
- List applications by specifying the environment using apictl. (It may asked to log in to envronment. Login as one of the above users)
  ![image](https://user-images.githubusercontent.com/25246848/77034327-a5db9780-69cf-11ea-8578-b50545e03a98.png)
- Try listing applications by log in to the environment as the other user as well.
  ![image](https://user-images.githubusercontent.com/25246848/77034377-d02d5500-69cf-11ea-90f3-5287c74b395f.png)

**Comment by npamudika** [comment]
One more addition, once we fixed this we will be able to list all the applications in a tenant, and we need to provide the ability to filter it further to get a list of applications of a particular owner by providing a parameter. And the particular helper command should be updated with the -o (--owner) details. Earlier, -o (--owner) parameter didn't work properly. Currently we have modified the helper command's output as per https://github.com/wso2/product-apim-tooling/issues/142
