### ISSUE TITLE
API thumbnail is not getting updated when doing an API import --update

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim-tooling#216]
**Description:**
When we update the thumbnail of an API which is already imported to another environment, and re-export it and re-import the API with --update, the updated thumbnail is not getting reflected in the imported environment.

**Affected Product Version:**
Tested in 3.1.0-Alpha

**OS, DB, other environment details and versions:** 
Tested in Linux environment

**Steps to reproduce:**
1. Export an API from Dev environment.
2. Import the API to Prod environment.
3. Update the thumbnail of the API in Dev environment.
4. Re-export the API from Dev environment.
5. Re-import the updated API to Prod environment with --update command.
6. Check for the updated thumbnail of the API in Prod environment.

**Comment by wasuradananjith** [comment]
There are two thumbnail types that can be considered.
1. Images that can be uploaded as the thumbnail.
    ![image](https://user-images.githubusercontent.com/25246848/77641195-a81a9480-6f81-11ea-976f-dddae4086bf0.png)

2. Icons in the UI that can be used as thumbnails.
   ![image](https://user-images.githubusercontent.com/25246848/77641324-e2843180-6f81-11ea-8b85-04a633cb5264.png)

When considering the first type, irrespective of the image type (.jpg, .jpeg, .png, .gif, .bmp) the above procedure which was stated in the issue (Import, Export, Import with update) works perfectly without a problem. (Tested in Ubuntu 18.04.2 LTS)

But when considering the second type, there is a problem. When exporting an API through apictl (or downloading an API using UI) the thumbnail icon is not getting exported into the archive (even the thumbnail URL is not getting saved in a file). Consider the below scenario which makes this more problematic. 
- I am creating an API in one (dev) environment and uploading an image for that API. Then I download/export it and will import it to another environment (prod). The API will be successfully imported with the image. 
- Now, I change the API image to an icon available in the UI in the dev environment. Again I re-download/export it and re-import it to the prod environment with the --update flag. 
- But the previous image of the API in the prod environment will not be overridden by the icon which I selected from the UI. So this might be an issue.

IMO, this could be solved from the APIM side.

**Comment by uvindra** [comment]
If the exported archive does not contain the icon, then this is something that needs to be addressed at APIM level

**Comment by npamudika** [comment]
Material UI icon's ID is stored in a json file and stored in the registry. Now that json is not getting packed into the archive. Need to export that json into the archive and check for the import functionality.
