### ISSUE TITLE
Documentation Requirements for APICTL 3.1.0 Release

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#225]
**Description:**
This is to keep track of the documentation requirements of APICTL 3.1.0 Release.
Let's add a comment to this issue with the details of the changes we need to do to the documentation.

**Comment by malinthaprasan** [comment]
Move "get-keys" documentation from Getting Started section to the "CI/CD" section. "get-keys" is used for generating a token to run a test suite for the API during CI/CD pipeline.

**Comment by malinthaprasan** [comment]
# Test doc issue
Description

**Comment by wasuradananjith** [comment]
<h2>Make API provider name optional when exporting an API</h2>

Document changes have already been done. https://github.com/wso2/docs-apim/issues/847

**Comment by wasuradananjith** [comment]
<h2>Change the description of custom_role who has only API Create permission</h2>

Document changes to be done and the error message should be changed.

**Comment by malinthaprasan** [comment]
## Use 'ExposeEndpointPassword' config, if endpoint passwords need to be exported
By default, endpoint passwords are made empty when API is exported. Need to add `"ExposeEndpointPassword" : "true"` in `/_system/config/apimgt/applicationdata/tenant-conf.json` to get it exported. Otherwise, the issue https://github.com/wso2/product-apim-tooling/issues/143 can be observed.

**Comment by wasuradananjith** [comment]
<h2>Modify the api_params.yaml file with security parameters</h2>

**Comment by wasuradananjith** [comment]
<h2>Improve documentation on CI/CD with WSO2 API Manager (apictl)</h2>

**Comment by malinthaprasan** [comment]
## Environment variable support for project files

Details are in https://github.com/wso2/product-apim-tooling/pull/243

**Comment by npamudika** [comment]
## Change documentation for new environment set commands

Details are in https://github.com/wso2/product-apim-tooling/issues/224

**Comment by wasuradananjith** [comment]
<h2>Need documentation on "apictl export-apis"</h2>

**Comment by npamudika** [comment]
### Need to add documentation on how to add scopes for a resource when creating an API using the swagger file

**Comment by wasuradananjith** [comment]
<h2>Need a separate page to describe Configuring Environment Specific Parameters</h2>

In the documentation of API Controller, the "Configuring Environment Specific Parameters" topic is in two pages, namely in "API Manager Documentation 3.1.0 Importing APIs Via Dev First Approach" page and in "Migrating APIs to Different Environments" page. 

As the solution, "Configuring Environment Specific Parameters" can be moved to a separate page under "Advanced Topics" and refer that page when necessary.
