### ISSUE TITLE
Support for enviroment level public certificate installation for secure https communication

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim-tooling#235]
**Description:**
This requirement was identified when addressing https://github.com/wso2/product-apim-tooling/issues/137 when apictl is not being used in _insecure_ mode.

Currently we do not have provision for providing the public certificate of the APIM server to the apictl. Since the apictl needs to deal with multiple environments, this means that we need to be able to provide a certificate per an environment.

Therefore including this as part of the add_env command seems most suitable. We can specify a new flag such as --cert in order provide the path of the .pem file. The command would then look like,

```
apictl add-env -e dev \
            --registration https://localhost:9444/client-registration/v0.15/register \
            --apim https://localhost:9444 \
            --token https://localhost:8244/token \
            --cert /home/user/public.pem
```

We will also need to store the cert in the ~/.wso2apictl folder as follows,

```
.wso2apictl
      |
      |--------- certs
                      |
                      |--------- <env>
                                       |
                                       |--------- <certname>.pem
```

Depending on the env that is being used in a given https call, the respective certificate will be picked and used by apictl.

**Affected Product Version:**
3.0.0, 3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by uvindra** [comment]
Possible candidate for implementing this is https://github.com/pavel-v-chernykh/keystore-go. We need to evaluate this and see.

**Comment by 1akshitha** [comment]
Instead of the approach suggested in the issue, all the certs will be stored in /home/.wso2apictl/certs directory without any environment level hierarchy. All the certificates of CAs trusted by the OS will be imported by default.
