### ISSUE TITLE
addEnv empty Endpoints

### ISSUE THREAD

**Issue by jpvadell** [wso2/product-apim-tooling#26]
**Description:**
If I add the admin and AppList endpoint as parameters when create a new environment, appears empty at main_config.yml 

You need to add at addEnv.go

	if envEndpoints.AppListEndpoint != "" {
		validatedEnvEndpoints.AppListEndpoint = envEndpoints.AppListEndpoint
	}

	if envEndpoints.AdminEndpoint != "" {
		validatedEnvEndpoints.AdminEndpoint = envEndpoints.AdminEndpoint
	}

**Steps to reproduce:**

Create a new environment with admin and appList endpoints.

**Comment by uvindra** [comment]
Fixed in https://github.com/wso2/product-apim-tooling/commit/ce654c69d80c17c0b3ee04356444f077658fbb4c
