### ISSUE TITLE
apictl login failed

### ISSUE THREAD

**Issue by rajputvishwas** [wso2/product-apim-tooling#272]
**Description:**

I am trying to login to env using apictl, but it fails with an error

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2 3.0
apictl 3.1

**OS, DB, other environment details and versions:**    
windows 10
**Steps to reproduce:**

Start wso2 apim

Create an environment
apictl add-env -e dev --registration https://localhost:9443/client-registration/v0.15/register --apim https://localhost:9443 --token https://localhost:8243/token

Login to environment

D:\test>apictl login dev
Username:admin
Password:
apictl: Error in connecting. Reason: Post "https://localhost:9443/client-registration/v0.15/register/client-registration/v0.16/register": x509: certificate signed by unknown authority
Exit status 1

D:\test>apictl login dev -k
Username:admin
Password:
Error occurred while login :  Request didn't respond 200 OK: 404

**Related Issues:**

**Comment by npamudika** [comment]
Hi @rajputvishwas,

APICTL 3.1.0 version is only compatible with API Manager 3.1.0 version.

If you are using API Manager 3.0 version, you need to use https://github.com/wso2/product-apim-tooling/releases/tag/v3.0.1.
Please follow https://apim.docs.wso2.com/en/3.0.0/learn/api-controller/getting-started-with-wso2-api-controller/ for APICTL 3.0.1 version.

If you are planning to use APICTL 3.1.0 version, please download API Manager 3.1.0 version and try the tool with that. 
Please note, we have modified add environment commands by changing the endpoint values. Please follow https://apim.docs.wso2.com/en/latest/learn/api-controller/getting-started-with-wso2-api-controller/ for more details.

Please do let us know if you require any further assistance regarding this. We would happy to assist you :)

**Comment by npamudika** [comment]
Closing the issue as answered. Please do reopen if you have any further queries regarding this.

**Comment by soubhagya333** [comment]
i need migration of wso2am-3.1.0 to 3.2.0 but all the migaration will going currect and getting of the all apis,products and users except of applications in dev portal so i use ./apictl for migrating app from 3.1.0 to 3.2.0 please help me i am geeting this error while when i am importing an app. i export app with wso2am-3.1.0 ---like app name is testapp.zip .i exported in dev env

./apictl import-app -f /home/ecas0038/.wso2apictl/exported/apps/dev/admin_testapp.zip -e production -k
Login to production
Username:admin	
Password:
apictl: Error in connecting. Reason: Post "https://idp.com:9444/client-registration/v0.17/register": dial tcp 103.143.210.123:9444: i/o timeout (Client.Timeout exceeded while awaiting headers)
Exit status 1


wso2am-3.2.0 error logs

[2022-02-17 10:30:32,772] ERROR - OAuth2Service Error while finding application state for application with client_id: D_KGTYVg7zwfGzDEqP1Znro2X40a
[2022-02-17 10:31:36,715] ERROR - ExportApiServiceImpl No application found with name testapp owned by admin
