### ISSUE TITLE
Cannot use APICTL with old APIM versions

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim-tooling#276]
**Description:**
Now, with the release of APICTL 3.1.0 version, it cannot be used with the old APIM versions and it'll be a good addition if we can support for the old APIM versions too.

**Comment by malinthaprasan** [comment]
This cannot be fixed due to the compatibility issues that are very hard to maintain.
For a new APIM version, first the old APIM pack needs to be migrated to a new version and then the APIs needs to be exported from the new API Manager version.
