### ISSUE TITLE
Cannot import an API when the providerName in the api.yaml file contains an @ symbol

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#308]
**Description:**
When importing an API, if the ```providerName``` in the api.yaml file contains an @ symbol (eg:- admin@test.com) an error will be displayed as below from the API Controller.
```
wasura@wso2-ThinkPad-T520:~/Desktop$ apictl import-api -f ./Petstore -e test
Error importing API.
Status: 500 
Response: {"code":500,"message":"Internal server error","description":"Error while importing API","moreInfo":"","error":[]}
apictl: Error importing API Reason: 500 
Exit status 1
```
The error in the API Manager will look like below.
```
[2020-05-13 20:37:37,804] ERROR - GovernanceArtifactManager Failed to add artifact: artifact id: 8296cb72-6343-4ba1-aee9-708b4e782adb. Unable to put resource The path '/_system/governance/apimgt/applicationdata/provider/admin@test.com/SwaggerPetstore/1.0.5/api' contains one or more illegal characters (~!@#;%^*()+={}|\<>"',)
org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource The path '/_system/governance/apimgt/applicationdata/provider/admin@test.com/SwaggerPetstore/1.0.5/api' contains one or more illegal characters (~!@#;%^*()+={}|\<>"',)

```
When you manually replace the @ symbol in the ```providerName``` with -AT- (eg:- admin-AT-test.com), the import happens successfully.

**Suggestion:** 
Replace @ symbol in the ```providerName``` with -AT- from the API Controller, before calling the REST API in API Manager.

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
APICTL 3.1.0

**Steps to reproduce:**
1. Create a tenant user in a particular domain (In my case the domain is test.com) as "admin@test.com" from API Manager. (Make sure this user has required permissions and scopes to import an API)
2. Log in to the API Controller as the above-created user using ```apictl login``` command.
3. Initialize an API using the ```apictl init``` command. (eg:- ```apictl init Petstore --oas https://petstore.swagger.io/v2/swagger.json```)
4. Open the api.yaml file in the Meta-Information directory which is inside the project folder and rename the provider name to the earlier created tenant user (In my case admin@test.com).
5. Try to import the API and you will get the above errors which are shown in the **Description** section.

**Comment by uvindra** [comment]
This scenario cannot be reproduced during a standard export scenario, which handles the '@' symbol correctly ensuring that it is replaced by '_AT_'. This scenario was reproduced by manually editing the exported file. Therefore closing this ticket.
