### ISSUE TITLE
Distinguish whether the APICTL tasks happen by a CI/CD flow or not

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#313]
**Description:**
Currently, the API Controller can be used in two scenarios as stated below. We need a way to distinguish those two scenarios when performing tasks using the API Controller.

1. CI/CD Flow
To identify this we need to define a new scope. This is basically for a non-human user (eg:- Jenkins). If a user has this scope, no permission checks or access control checks will be performed. This scope can be enforced by creating a new role that has bound to this scope.

2. Developer first approach
Mainly, this scenario will be used by a human user. If a user does not have the above-stated scope, the user will belong to this category and all the required permission and access control checks will be performed. (Currently, this support is available)

**Suggested Labels:**
Type/Improvement

**Comment by uvindra** [comment]
Do we still need this?

**Comment by wasuradananjith** [comment]
The expectation is already fulfilled when resolving [1] in APICTL 3.2.0. Hence, we can close this issue.

[1] https://github.com/wso2/product-apim-tooling/issues/372
