### ISSUE TITLE
Need support to set up api_params.yaml for multiple endpoints

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#322]
**Description:**
When importing an API using the API Controller, there is a need to mention multiple endpoints in the api_params.yaml file to handle the **load balancing** and **failover** scenarios, because the publisher portal already supports those.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
@wasuradananjith 

**Affected Product Version:**
APICTL 3.1

**Related Issues:**
https://github.com/wso2/product-apim-tooling/pull/321

**Comment by BLasan** [comment]
Fixed by [api-manager-issue-172](https://github.com/wso2/api-manager/issues/172) for APICTL-3.1
