### ISSUE TITLE
Improve the reusability in the code and remove code duplication

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#340]
**Description:**
Currently both cmd related logic and cli internal application related logic are both included in `cmd` package. This makes the code less reusable. The methods introduced by the package doesn't also have a clear seperation between the cmd inputs and method related inputs. 

Examples: 

1. `ImportAPI` method takes below from the method inputs. But internally it is reading package level cmd input variables. Because of this, ImportAPI method is not easily callable from another method.

```
func ImportAPI(credential credentials.Credential, importPath, adminEndpoint, exportDirectory, apiParamsPath string) error {
...
	if paramsPath != "" {
		//Reading API params file and populate api.yaml
		err := injectParamsToAPI(apiFilePath, paramsPath, importEnvironment)  // importEnvironment here are read from the package level
		if err != nil {
			return err
		}
	}
}

```
2. Methods like `getAPIId` is duplicated across several files. 

```
importAPI,go: func getApiID(name, version, environment, accessOAuthToken string) (string, error) {
deleteAPI.go: func getAPIId(accessToken string) (string, error) {
changeAPIStatus.go: func getAPIIdForStateChange(accessToken string, credential credentials.Credential) (string, error) {
```

**Comment by npamudika** [comment]
Fixes are included in https://github.com/wso2/product-apim-tooling/pull/345
