### ISSUE TITLE
Not able to import API in APICLI 2.0.7

### ISSUE THREAD

**Issue by Senthuran100** [wso2/product-apim-tooling#341]
**Description:**
Say there is an API with the context /inventory/sample1 and when we import the API with context sample1 using the API CLI tool we are getting an error as below.
`Response: Error occurred while adding the API [ORDS-1.0.0]. A duplicate context[/sample1/1.0.0] already exists`
This behaviour is not observed in the UI. 

**Suggested Labels:**
APICLI

**Affected Product Version:**
APIM 2.6.0 , APICLI 2.0.7

**Steps to reproduce:**
- Create an API with context /inventory/sample1
- Then import an API using APICLI 2.0.7 having a context sample1

**Comment by npamudika** [comment]
Tested this in the latest APICTL 3.1.2 release with APIM 3.1.0 and this cannot be reproduced.

**Comment by npamudika** [comment]
Fixed in APIMCLI 2.0.8 version.
