### ISSUE TITLE
SOAP to REST conversion logic not exported or imported with API when using APICTL 3.0.1 and APIM 3.0.0

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#346]
**Description:**
When exporting an API created from as mentioned in the docs titled as **Generate REST API from SOAP Backend** in [1], the exported .zip does not contain the SOAP to REST conversion logic. 

Also, even if you have an already exported API with the SOAP to REST conversion logic in the .zip (Suppose you exported it from APIM 3.1.0, since this issue does not exist there), when you import it the logic does not get imported.

**Solution:** Backport the fix https://github.com/wso2/carbon-apimgt/pull/7973 done in APIM 3.1.0 to 3.0.0.

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**
@wasuradananjith 

**Affected Product Version:**
APICTL 3.0.1
APIM 3.0.0

**OS, DB, other environment details and versions:**    
Ubuntu 18.04.4 LTS

**Steps to reproduce:**
1. Create an API as mentioned in [1].
2. Export it using APICTL 3.0.1 and the SOAP to REST conversion logic will not be there. (Check [2])
3. Get [3] (which consists the SOAP to REST conversion logic) and import it using APICTL 3.0.1. When you check the Inflow and Outflow mediation by selecting Resources in the UI, the SOAP to REST conversion logic will not be there.

**Related Issues:**
For APIM 3.1.0 this has been fixed (https://github.com/wso2/product-apim/issues/6868)

[1] https://apim.docs.wso2.com/en/3.0.0/learn/design-api/create-api/generate-rest-api-from-soap-backend/
[2] [PhoneVerification_1.0.zip](https://github.com/wso2/product-apim-tooling/files/4798597/PhoneVerification_1.0.zip)
[3] [PhoneVerification_1.0.zip](https://github.com/wso2/product-apim-tooling/files/4798602/PhoneVerification_1.0.zip)

**Comment by npamudika** [comment]
This has been fixed via a WUM update for APIM 3.0.0
