### ISSUE TITLE
Not able to update the custom mediation inflow sequence in APICLI 2.0.3 and in APICLI 2.0.7

### ISSUE THREAD

**Issue by riyazathali** [wso2/product-apim-tooling#369]
**Description:**
When updating the API with the newly created custom mediation in sequence to the second environment, there is no error in wso2carbon.log. It shows all the steps are successful. But when we checked on the publisher of the second environment, it contains an old API mediation in-sequence.

**Suggested Labels:**
APIM 2.6.0 and API CLI 2.0.3
APIM 2.6.0, API CLI 2.0.7

**Steps to reproduce:**
1. Export an API with the existing custom mediation in-sequence from the first environment(productionnew).
EX: ./apimcli export-api -n GetPatient -v 1.0.0 -e productionnew --provider admin -k --verbose
2. Import the API to the second environment(productionnew1).
EX: ./apimcli import-api -f .wso2apimcli/exported/apis/productionnew/GetPatient_1.0.0.zip -e productionnew1 -k --preserve-provider=true --update --verbose
3. Unzip the already exported API zip file(.wso2apimcli/exported/apis/productionnew/GetPatient_1.0.0.zip) and change the mediation sequence in the /Sequences/in-sequence/Custom directory(.wso2apimcli/exported/apis/productionnew/GetPatient-1.0.0/Sequences/in-sequence/Custom) by modifying and zip the directory again. (Please make the same of the zip file as GetPatient_1.0.0.zip).
4. Again Import the API to the second environment(productionnew1) with the same command with --update flag with the modified zip file.
EX: ./apimcli import-api -f /Users/ali/.wso2apimcli/exported/apis/productionnew/GetPatient_1.0.0.zip -e productionnew1 -k --preserve-provider=true --update --verbose
5. When checking the publisher UI of the second environment, the same old custom mediation sequence is there and not getting updated with the latest modified sequence.

Also, Here please consider we have tried to make a change in the custom mediation sequence in the first environment via publisher UI and export the API from there and import it to the second environment also giving the same result. (Here we did not do the modification by unzipping the exported zip file.)

**Comment by npamudika** [comment]
Checked in the latest APICTL 3.2.0-Alpha release (https://github.com/wso2/product-apim-tooling/releases/tag/v3.2.0-alpha) with APIM 3.2.0-Alpha and this issue cannot be reproduced.

**Comment by npamudika** [comment]
This is a bug in APICTL 2.0.x version and has been fixed in the api-import-export-2.6.0-v16.war file.

**Comment by npamudika** [comment]
Please refer updated documentation (https://docs.wso2.com/display/AM260/Initializing+projects+using+the+CLI+Tool) for the **updated webapp** which includes the fixes.
