### ISSUE TITLE
[Import/Export-CLI] Implement Scope definitions in token generation

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim-tooling#37]
**Description:**
Related scope definitions are not added yet when generating tokens. This has to be added considering each use case of tokens

**Affected Product Version:**

 2.0.0 (WSO2 APIM 3.0.0 related Tooling - Import/export CLI tool)

**Comment by dinusha92** [comment]
This has been fixed with the #39 PR. Hence closing the issue.
