### ISSUE TITLE
Token type is not changed when the token type is set (changed) between two consecutive get-keys commands

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#397]
**Description:**
After generating keys for a particular API/API Product for the first time, when we change the token type to another type, and try to generate keys again, the type of the token is still the previous type, not the updated type.

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
APICTL 3.2.0-Pre Beta
APIM 3.2.0-Beta

**OS, DB, other environment details and versions:**    
OS: Ubuntu 20.04 LTS

**Steps to reproduce:**
1. Make sure to have a published API (eg:- PizzaShackAPI) inside the APIM.
2. Generate keys using the below command for the above-stated API.
   ```
   apictl get-keys -n PizzaShackAPI -v 1.0.0 -e production
   ```
3. You will receive a JWT token as shown below.
   ```
   eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhdWQiOiJNckxXcTRONHpwQUxPbXFPdjZYOXV0ZWZyR1VhIiwibmJmIjoxNTk0MTk1NzEzLCJhenAiOiJNckxXcTRONHpwQUxPbXFPdjZYOXV0ZWZyR1VhIiwic2NvcGUiOiJhbV9hcHBsaWNhdGlvbl9zY29wZSBiYXJUZXN0MSBmb29UZXN0MSIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0M1wvb2F1dGgyXC90b2tlbiIsImV4cCI6MTU5NDE5OTMxMywiaWF0IjoxNTk0MTk1NzEzLCJqdGkiOiI2M2VjMTUxNC1mNjVkLTRmYzgtOGVkYy0xY2JhNTA4MGMyOTEifQ.to6cSkjoG5BAnK63r8EibzwbQarPlmI_WdC443l2zce3n4EKQxE9fsMacVPk7-0L3_QYA6-FUJE8jNjv-n-z0VrBjr-5Xs5AfEI3CU_25czXUC9bSxIvTnb3wEOg-6vRMGuIurAb3TsAizT6X1WyqgHFKNFQFdC5T0EIVGeYkjBJfnxzdjs4Vp40TxcvcdhzkHaKzS88LQKX8cA6yCDWg6elLYEO6CU5K4o4GaK-vejBsehHp9v4ckc1mb71scRXEyZN70a4-ci7_y_UtzUARly-1i6Colu4YL8pl4NSCdpUkCOTStbRKd35zy1EDKaW-EvlLeQ23nHsnTiiLoWlsw
   ```
4. Change the token type to OAUTH using the below command.
   ```
   apictl set --token-type OAUTH
   ```
5. Generate a key again for the same API using the command mentioned in Step 2. You will still receive a JWT token, not an OAUTH one.

**Comment by wasuradananjith** [comment]
**Option 1**
As a workaround, before changing the token type using "apictl set --token-type", delete the already existing application.

**Option 2**
The fix can be done as follows.
1. Fetch the already existing application (default-apictl-app) in the corresponding environment before generating keys.
2. Check whether the token type of that application is matched with the token type stored in **main_config.yaml** in .wso2apictl repository.
3. If the token type differs, then update the application with the token type in **main_config.yaml** file.
4. Then generate keys.

**Comment by malinthaprasan** [comment]
Token type change not allowed an is removed from https://github.com/wso2/product-apim-tooling/pull/441
