### ISSUE TITLE
'Add environment' example endpoints are incorrect

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim-tooling#40]
**Description:**

Environment related endpoints that should be defined when adding an Environment for Import/Export CLI tool, are incorrect.

Below endpoints,
--publisher https://localhost:9292/api/am/publisher/v1.0
--registration https://localhost:9443/identity/connect/register
--token https://localhost:9443/oauth2/token

should be changed to,
--publisher https://localhost:9443/api/am/publisher/v1.0
--registration https://localhost:9443/api/identity/oauth2/dcr/v1.0/register
--token https://localhost:9443/api/auth/oauth2/v1.0/token

in, https://docs.wso2.com/display/AM300/Migrating+the+APIs+to+a+Different+Environment#MigratingtheAPIstoaDifferentEnvironment-ExportinganAPI

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-apim-tooling/issues/38
The fixes made on README here should be reflected in the docs too.

**Comment by dinusha92** [comment]
This issue is no longer relevant as the aforementioned issue is not compatible with current 3.0.0 migration docs. Hence closing the ticket.
