### ISSUE TITLE
API Import fails on self-signed certificate with --insecure or -k option

### ISSUE THREAD

**Issue by robbla** [wso2/product-apim-tooling#41]
The 1.1.0 apimcli import api function does not use the --insecure or -k flag when importing on an ootb API Manager with self sgined certificate as can be seen in the image below.  

![afbeelding](https://user-images.githubusercontent.com/11582659/43766207-2388fc8c-9a32-11e8-951e-d2b9a29f19a9.png)

**Comment by praminda** [comment]
Hi @robbla 
It seems `-k` option doesn't properly activate insecure mode in your case. I tried the same scenario on Windows 10 Env with latest [apimcli tool release](https://github.com/wso2/product-apim-tooling/releases/tag/v1.2.0).
Which version did you try and on what Environment?

**Comment by dinusha92** [comment]
Hi @robbla , this has not been able to reproduce in the latest APIM CLI at the moment (3.0.0-beta). And providing -k option should solve this issue. Hence closing the issue.
Please feel free to reopen the issue if the issue continues to occur.
