### ISSUE TITLE
apimcli fails on import with confusing error msg

### ISSUE THREAD

**Issue by robbla** [wso2/product-apim-tooling#42]
Importing an API using  apimcli throws a confusing error
ZipFilePath: /opt/wso2/.wso2apimcli/exported/apis/opt/wso2/.wso2apimcli/exported/apis/APIM-DEV/PizzaShackAPI_1.0.0.zip
apimcli: Error creating request. Reason: open /opt/wso2/.wso2apimcli/exported/apis/opt/wso2/.wso2apimcli/exported/apis/APIM-DEV/PizzaShackAPI_1.0.0.zip: no such file or directory
Exit status 1

I am using two API environments on the same server, export the PizzaShack API and try to import it into the other one. 

CA cert is added to Centos, API environments work as they should

these are the definitions

apimcli add-env -n APIM-DEV --registration https://api.blog.yenlo:9443/client-registration/v0.13/register --apim https://api.blog.yenlo:9443 --token https://api.blog.yenlo:8243/token --import-export https://api.blog.yenlo:9443/api-import-export-2.5.0-v1 --admin https://api.blog.yenlo:9443/api/am/admin/v0.13     --api_list https://api.blog.yenlo:9443/api/am/publisher/v0.13/apis --app_list https://api.blog.yenlo:9443/api/am/store/v0.13/applications

./apimcli add-env -n APIM-TEST --registration https://api.blog.yenlo:9444/client-registration/v0.13/register --apim https://api.blog.yenlo:9444 --token https://api.blog.yenlo:8244/token --import-export https://api.blog.yenlo:9444/api-import-export-2.5.0-v1 --admin https://api.blog.yenlo:9444/api/am/admin/v0.13     --api_list https://api.blog.yenlo:9444/api/am/publisher/v0.13/apis --app_list https://api.blog.yenlo:9444/api/am/store/v0.13/applications

![afbeelding](https://user-images.githubusercontent.com/11582659/43963759-811aa590-9cbb-11e8-9cc4-ef1d395625f4.png)

**Comment by rmsamitha** [comment]
Hi Robbla,

This should be because the api zip which is going to be imported is not available in the given path. Can you please verify it?
It it is there, then please copy the PizzaShackAPI_1.0.0.zip into a different directory other than in /opt/.. and test again. (for example copy it to ~/Desktop/ )

**Comment by Mariangela** [comment]
@robbla , were you able to test what Samitha mentioned?

**Comment by kasvith** [comment]
You can try `apim-import APIM-DEV/PizzaShackAPI_1.0.0.zip -e APIM_TEST`
It seems tool has appended path twice and that causes the problem. The new version of tool support correctly looking up for zip files or directories on nonworking directory also

**Comment by dinusha92** [comment]
Since the latest version of the cli tool (v3.0.0-beta) contains the fix, this issue will be marked as closes.
Please feel free to reopen the issue if there's any concern.
