### ISSUE TITLE
Subscribed APIs duplicates in the imported Applications

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim-tooling#424]
**Description:**
When I export and import the APIs and applications from one tenant to another I could observe that the subscription details of the API are not there, but those details are with the imported applications. The same application can be subscribed to the same API again.

**Steps to reproduce:**
1. Create environment.
```apimcli add-env -n Development3 --registration https://localhost:9443/client-registration/v0.14/register --apim https://localhost:9443 --token https://localhost:8243/token --import-export https://localhost:9443/api-import-export-2.6.0-v14 --admin https://localhost:9443/api/am/admin/v0.14 --api_list https://localhost:9443/api/am/publisher/v0.14/apis --app_list https://localhost:9443/api/am/store/v0.14/applications```

2. Login with a tenant user and export APIs and Applciations.
``` apimcli login Development3 -u tenant@test.com -p test12 -k```
``` apimcli export-api -n LatestToolAPI -v 1 -r admin -e Development3 -k ```
``` apimcli export-app -n LatestAPPLICATION -o admin -e Development3 -k --insecure```

3. Logout and login with another user.
``` apimcli logout Development3 ```
``` apimcli login Development3 -u admin -p admin -k```

4. Import the APIs and Application
``` apimcli import-api -f /Users/madhuriprabhaswari/.wso2apimcli/exported/apis/Development3/LatestToolAPI_1.zip  -e Development3 -k --preserve-provider=false --verbose --update```
``` apimcli import-app -f /Users/madhuriprabhaswari/.wso2apimcli/exported/apps/Development3/admin_LatestAPPLICATION.zip -e Development3 -k --verbose```

API Manager version: 2.6.0 -t 1586110914316
Apimcli tool version: 2.0.3 and 2.0.8
Import-export .war file version: v14 and v16 

### **Issue:**

Subscription details in imported Application:
![image](https://user-images.githubusercontent.com/28176167/88814982-67a18080-d1d8-11ea-9ab9-2212896664b9.png)

When clicking on that API, the same application can be seen in the application list as below.
![image](https://user-images.githubusercontent.com/28176167/88815286-cebf3500-d1d8-11ea-8f18-eead09e45567.png)

If I subscribed to that API with the same application, I can see both subscriptions as below.
![image](https://user-images.githubusercontent.com/28176167/88815552-1776ee00-d1d9-11ea-8e7b-dd124cd66451.png)

In the publisher portal, imported API subscriptions can be seen as below.
![image](https://user-images.githubusercontent.com/28176167/88816037-9a984400-d1d9-11ea-804a-0749f1c400df.png)

**The above behavior is the same for the latest API Manager version and apictl tool as well.** 

![image](https://user-images.githubusercontent.com/28176167/88824712-552d4400-d1e4-11ea-8c75-df1370e84572.png)

The test version details are as follows.

- API Mnaager version: 3.1.0 -t 1593095757692
- apictl tool version: 3.1.3

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Related Issues:**

**Comment by Chamindu36** [comment]
This is expected behavior when the import-export process happens between tenants. What actually happens here is not a duplication. Even though same API is visible for the app these APIs belong to two different providers. Therefore this is two subscriptions that handled by same application where subscribed APIs happened to be owned by two different tenants.
