### ISSUE TITLE
A short flag is used for different purposes

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim-tooling#46]
**Description:**
The -r short flag has been used it different places [1] and [2] for different uses. This is not a good standard as it can be confusing to the user.

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**
2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
[1] **Scenario 1**
When I run the following command, I see that -r is used to define whether you need to preserve the owner or not.
./apimcli import-app --help

> Import an Application to an environment
> Examples:
> apimcli import-app -f qa/apps/sampleApp.zip -e dev
> apimcli Import App -f staging/apps/sampleApp.zip -e prod -o testUser -u admin -p admin
> apimcli import-app -f qa/apps/sampleApp.zip --preserveOwner --skipSubscriptions -e prod
> 
> Usage:
>   apimcli import-app (--file <app-zip-file> --environment <environment-to-which-the-app-should-be-imported>) [flags]
> 
> Flags:
>   -e, --environment string   Environment from the which the Application should be imported (default "default")
>   -f, --file string          Name of the Application to be imported
>   -h, --help                 help for import-app
>   -o, --owner string         Name of the target owner of the Application as desired by the Importer
>   -p, --password string      Password
>   -r, --preserveOwner        Preserves app owner
>   -s, --skipSubscriptions    Skip subscriptions of the Application
>   -u, --username string      Username
> 
> Global Flags:
>   -k, --insecure   Allow connections to SSL endpoints without certs
>       --verbose    Enable verbose mode

[2] **Scenario 2**
When I run the following command,  I see that -r is used to define the provider.
./apimcli export-api --help

> Export APIs from an environment
> Examples:
> apimcli export-api -n TwitterAPI -v 1.0.0 -e dev --provider admin
> apimcli export-api -n FacebookAPI -v 2.1.0 -e production --provider admin
> NOTE: all three flags (--name (-n), --version (-v), --provider (-r)) are mandatory
> 
> Usage:
>   apimcli export-api (--name <name-of-the-api> --version <version-of-the-api> --environment <environment-from-which-the-api-should-be-exported>) [flags]
> 
> Flags:
>   -e, --environment string   Environment to which the API should be exported (default "default")
>   -h, --help                 help for export-api
>   -n, --name string          Name of the API to be exported
>   -p, --password string      Password
>   **-r, --provider string      Provider of the API**
>   -u, --username string      Username
>   -v, --version string       Version of the API to be exported
> 
> Global Flags:
>   -k, --insecure   Allow connections to SSL endpoints without certs
>       --verbose    Enable verbose mode
> examples:apimcli export-api -n TwitterAPI -v 1.0.0 -e dev --provider adminapimcli export-api -n FacebookAPI -v 2.1.0 -e production --provider adminNOTE: all three flags (--name (-n), --version (-v), --provider (-r)) are mandatoryUsage:  apimcli export-api (--name <name-of-the-api> --version <version-of-the-api> --environment <environment-from-which-the-api-should-be-exported>) [flags]Flags:  -e, --environment string   Environment to which the API should be exported (default "default")  -h, --help                 help for export-api  -n, --name string          Name of the API to be exported  -p, --password string      Password  -r, --provider string      Provider of the API  -u, --username string      Username  -v, --version string       Version of the API to be exportedGlobal Flags:  -k, --insecure   Allow connections to SSL endpoints without certs      --verbose    Enable verbose mode

**Related Issues:**

**Comment by kasvith** [comment]
I think we can remove these short flags and use full flag instead. Even using another character instead of `-r` also can confuse the users.

**Comment by kasvith** [comment]
Will remove short flags and it will be a breaking change. Need to inform users about it

**Comment by dinusha92** [comment]
This has been fixed. Hence closing the issue.
