### ISSUE TITLE
./apictl uninstall wso2am-operator will not remove all k8s artifacts related to the operator

### ISSUE THREAD

**Issue by sajithab** [wso2/product-apim-tooling#471]
**Description:**
`./apictl uninstall wso2am-operator` will not remove the ClusterRole, ClusterRoleBinding from the k8s.

**Affected Product Version:**
Tooling for APIM 3.1.0

**Steps to reproduce:**

1. ./apictl install wso2am-operator
2. ./apictl uninstall wso2am-operator
3. Then try to install the operator again and you will notice the ClusterRole, ClusterRoleBinding remains

**Comment by npamudika** [comment]
@renuka-fernando Will you be able to check on this?
