### ISSUE TITLE
Cannot override mutual SSL client certificates via api-params.yaml file

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim-tooling#477]
**Description:**
The mutual SSL client certificates cannot be overridden while doing the API import. We need to support this by adding a parameter to the api-params.yaml file as same as for the endpoint (backend) certificates.

**Affected Product Version:**
APIMCLI 2.0.8

**Comment by wasuradananjith** [comment]
Fixed in APIMCLI 2.0.9 version (https://github.com/wso2/product-apim-tooling/releases/tag/v2.0.9)
