### ISSUE TITLE
Feature request - provide a mechanism to export all available APIs

### ISSUE THREAD

**Issue by chintana** [wso2/product-apim-tooling#48]
**Description:**
Currently when a user creates a new environment, and want to import all available APIs from a different environment, a script or a program has to be written to get all available APIs, export those in a loop and then import all of those into the new environment.

Current output format of apimcli is not script friendly and it takes an effort to filter and sanitize the list. So an inbuilt option to export all available APIs will make life easy.

**Affected Product Version:**
API Manager 2.6.0

**Comment by dinusha92** [comment]
This is supported currently. 
Please refer this document for more info: https://github.com/wso2/product-apim-tooling/blob/v3.0.0-beta/import-export-cli/docs/apimcli_export-apis.md
Hence I will close this issue.
If there's any concern, please feel free to reopen the issue.
