### ISSUE TITLE
Username with "@" gives invalid input error when installing api-operator

### ISSUE THREAD

**Issue by Jayanie** [wso2/product-apim-tooling#480]
**Description:**
When entering the username with "@" in the process of installing the api-operator using **apictl install api-operator** command it gives an error as **Please try again. Invalid input.** 

**Steps to reproduce:**
1. apictl install api-operator
2. Enter a username with "@"
[](url)
![username](https://user-images.githubusercontent.com/35601987/93431257-83282e00-f8e1-11ea-824d-bb51c1a1da28.png)

**Comment by npamudika** [comment]
This issue is fixed in APICTL 3.2.1 release - https://github.com/wso2/product-apim-tooling/releases/tag/v3.2.1
