### ISSUE TITLE
apictl login to environment failing due to special character in password

### ISSUE THREAD

**Issue by mosesjos** [wso2/product-apim-tooling#490]
**Description:**
Unable to login into environment using apictl command. password contains special characters in carbon log we see that authentication is failing. But we can login into management, publisher and Devportal using same password

**Suggested Labels:**
APIM CLI tooling 3.1.0

**Suggested Assignees:**

**Affected Product Version:**

WSO2 APIM 3.1.0 
APICTL 3.1.0    

**Steps to reproduce:** 

$>./apictl login dev -u admin -p Wso2APiM$Admin$20 -k --verbose
Executed ImportExportCLI (apictl) on Sun, 27 Sep 2020 07:07:15 CEST
[INFO]: Insecure: true
Warning: Using --password in CLI is not secure. Use --password-stdin
Getting ClientID, ClientSecret: Status - 500
Error: %!s(<nil>)
Body: <ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat"><ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">org.apache.cxf.interceptor.security.AuthenticationException: Unauthenticated request</ns1:faultstring></ns1:XMLFault>
Error occurred while login :  Request didn't respond 200 OK: 500

CARBON LOG:

TID: [-1234] [] [2020-09-27 05:49:09,972]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - 'admin@carbon.super [-1234]' logged in at [2020-09-27 05:49:09,972+0200]
TID: [-1234] [] [2020-09-27 06:33:22,123]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - 'admin@carbon.super [-1234]' logged in at [2020-09-27 06:33:22,123+0200]
TID: [-1234] [client-registration/v0.16] [2020-09-27 07:07:15,768] ERROR {org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.BasicAuthenticationInterceptor} - Authentication failed: Invalid credentials

**Related Issues:**
https://github.com/wso2/product-apim-tooling/issues/131

**Comment by npamudika** [comment]
Thanks for reporting the issue. We will check and fix this in the next release.

**Comment by mosesjos** [comment]
@npamudika 

Good Day.

Kindly confirm whether we can expect the fix ?

Is there any alternative for the deployment ?

Thank you

**Comment by uvindra** [comment]
@mosesjos this issue is occurring because when the shell interprets the command it will try to resolve the strings after the '$' character as env variables. This is a unique scenario that occurs as a result of having symbol '$'.

To overcome this issue simply enclose the password value in single quotes in the command as follows,


$>./apictl login dev -u admin -p 'Wso2APiM$Admin$20' -k --verbose

This should allow you to overcome this issue.

**Comment by npamudika** [comment]
Closing the issue as the answer has been provided.
