### ISSUE TITLE
AlgoCombo Attribute is not getting added to endpoint config

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim-tooling#495]
**Description:**
When importing an API with a load balaned endpoint configuration in the params.yaml file, the created API's endpoint config does not contain algoCombo attribute.

This will cause an error while trying to attach a mediation sequence to the API. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Import an API with LB endpoints
Go to registry API view and explore the endpoint config field.

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by npamudika** [comment]
The fix will be available in the APIM CLI 2.0.10 patch release.
