### ISSUE TITLE
Allow API creators to use import/export REST APIs

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim-tooling#498]
In an API first approach, we expect the API developers to import or export APIs. Hence, it makes sense to give the default role 'Internal/creator' to access API Import/Export Admin REST APIs. 

If we add both creator and publisher roles to api_import_export scobe,
     - A user with either publisher or creator role can export APIs
    - A user with the creator role only can import an API with CREATED state
   - A user with both publisher and creator roles only can change the lifecycle and update the API

Would be also better to allow a user with a publisher role only to change the lifecycle.

**Comment by npamudika** [comment]
This is already addressed in the latest releases. Please refer https://apim.docs.wso2.com/en/latest/learn/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations/ for more information.

API Create permission is used to import an API in CREATED state,while both API Create and API Publish permissions are required to import an API in PUBLISHED state.

**Comment by dushaniw** [comment]
Thank you @npamudika . Since we have a new role "internal/devops" role with the least privileges mentioned in above-mentioned documentation, there is no longer required to by default allow api import to "internal/creator" or "internal/publisher" user.  Hence closing issue.

**Comment by npamudika** [comment]
Thanks @dushaniw for the confirmation. Yes, internal/devops role is introduced in **APICTL 3.2.0** release and it's now available in all the releases afterwards.
