### ISSUE TITLE
Error Initializing API Project When API Definition Contains 'y' or 'n' as Properties or Values

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim-tooling#506]
**Description:**

When initializing some API Projects using ```apictl init``` command, the following behaviour was observed. 

Type 1. When using [1], [2] as the API definition file, the following error message was printed.
```
apictl: Error initializing project Reason: unexpected map key type, got: bool
```
Type 2. When using [3], [4] as the API definition file, the following error message was printed.
```
apictl: Error initializing project Reason: json: cannot unmarshal bool into Go struct field SwaggerProps.paths of type string
```
These API definition files contain either 'y' or 'n' (without single quotes) as properties or values of properties, and it has been mentioned in [5] that yaml treats several values including y and n as as boolean values and this results in the error. It has also been mentioned that using quotes with 'y' or 'n' will solve the issue. 
But it is possible to import these APIs using the publisher UI and publish them to the devportal.

**Suggested Labels:**
Import-third-party-APIs

**Affected Product Version:**
apictl-3.2.0

**OS, DB, other environment details and versions:** 
OS: Ubuntu 20.04.1 LTS (64-bit)   

**Steps to reproduce:**
1. Initialize an API project using apictl and provide [1] or [2] as the --oas parameter value. This would result in the Type 1 error.
2. Initialize an API project using apictl and provide [3] or [4] as the --oas parameter value. This would result in the Type 2 error.

![keytype-error](https://user-images.githubusercontent.com/30455603/96566468-3de18c80-12e3-11eb-9365-f3117b584bca.png)

[1] https://github.com/APIs-guru/openapi-directory/blob/master/APIs/instagram.com/1.0.0/swagger.yaml
[2] https://github.com/APIs-guru/openapi-directory/blob/master/APIs/googleapis.com/poly/v1/openapi.yaml
[3] https://github.com/APIs-guru/openapi-directory/blob/master/APIs/omdbapi.com/1/swagger.yaml
[4] https://github.com/APIs-guru/openapi-directory/blob/master/APIs/atlassian.com/jira/1001.0.0-SNAPSHOT/openapi.yaml
[5] https://github.com/go-swagger/go-swagger/issues/1209

**Comment by npamudika** [comment]
Hi @hisanhunais,

We have further checked on this issue and y and n are considered as keywords in the yaml spec. According to the yaml spec, it is required to **provide such key words inside quotations** to overcome this kind of issues. Please refer https://yaml.org/type/bool.html for more details.

The other options are to **use a different key value or to use json as the format** (as this is specific to yaml format).

Similar issue - https://github.com/go-swagger/go-swagger/issues/490
