### ISSUE TITLE
Error when Importing API which contains Environment Variable like value - ${sample}

### ISSUE THREAD

**Issue by hisanhunais** [wso2/product-apim-tooling#508]
**Description:**

When importing [1] using `apictl import-api` command, the following error message was printed. 
```
apictl: Error importing API Reason: 11 errors occurred:
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
	* ${lambda_handler_invoke_arn} is required, please set the environment variable
```
It is possible to import this API using the publisher UI and publish to the devportal.

**Suggested Labels:**
Import-third-party-APIs

**Affected Product Version:**
apictl-3.2.0

**OS, DB, other environment details and versions:**    
OS: Ubuntu 20.04.1 LTS (64-bit)

**Steps to reproduce:**
1. Use [1] as the --oas parameter value and initialize an API project using apictl. 
2. Import this API using the import-api command.
![env_issue](https://user-images.githubusercontent.com/30455603/96673918-3ecafa80-1385-11eb-9c8a-0b0dde900d32.png)

[1] https://github.com/APIs-guru/openapi-directory/blob/master/APIs/mon-voyage-pas-cher.com/0.0.1/swagger.yaml

**Comment by npamudika** [comment]
Hi @hisanhunais,

The issue comes as you haven't defined the required environment variable(s) when importing the API. You need to first define the environment variable(s) as below before importing the API.

```
export lambda_handler_invoke_arn=http://localhost:8080/test
```

Once you have set the environment variable(s), while importing the API, the value(s) get(s) replaced successfully allowing you to import the API without an issue.

Closing this as this is not an issue.
