### ISSUE TITLE
Version of the CLI Tool for APIM 2.6.0 needs to be changed

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim-tooling#514]
**Description:**
The CLI Tool for APIM 2.6.0 and APIM 2.5.0 is the same at the moment. This needs to be changed.

**Suggested Labels:**
API-M 2.6.0

**Suggested Assignees:**
ChamilaA

**Affected Product Version:**
API-M 2.6.0

**OS, DB, other environment details and versions:**  
  

**Steps to reproduce:**
Run the following command in with the APIM 2.5.0 CLI tool and the APIM 2.6.0 CLI tool
`apimcli version`
The outcome is the same as follows:
apimcli Version: 1.1.0

**Related Issues:**

**Comment by npamudika** [comment]
This is not applicable now, hence closing the issue. For APIM 2.6.0, the apimcli version gives the following output.

```
Version: 2.0.10
Build Date: 2020-10-15 12:30:21 UTC
```
