### ISSUE TITLE
Handle importing an API version with default version set to true when an existing default API version exists

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim-tooling#533]
**Description:**
When an existing API version exists in an environment with default version set to true, we need to correctly handle what happens when a new API version is imported with default version to true.

We need to handle this in the exact same way that the APIM would allow for when creating a new API version in this scenario.

**Comment by wasuradananjith** [comment]
This has been fixed with https://github.com/wso2/carbon-apimgt/pull/9965. Hence, closing the issue.
