### ISSUE TITLE
API import/export tool to work on specific permissions instead of having super admin role

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/product-apim-tooling#536]
**Description:**

API import/export tool should work on specific permissions instead of having super admin role to the user using import/export tool

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kavishkafernando** [comment]
This feature has beenn implemented: https://apim.docs.wso2.com/en/latest/learn/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations/

**Comment by snehalsarode77** [comment]
Dear wso2 Team,
am trying to import api project. firstly created project by apictl init command. project folder is creatt. created new environment uat and trying to import that project.
**apictl import api -f C:\\Users\\3133\\Documents\\Openapi\\Api_Projects\\ -e uat --preserve-provider=false -k --update=true**
but while importing its f=giving me internal server error 
Error importing API.
Status: 500
Response: {"code":500,"message":"Internal server error","description":"The server encountered an internal error. Please contact administrator.","moreInfo":"","error":[]}
apictl: Error importing API Reason: 500
Exit status 1
Error on APIM Console: 
 ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
