### ISSUE TITLE
[Docs] Documentation changes are required for the newly introduced Source and Deployment directory structure.

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim-tooling#554]
**Description:**
The documentation should be updated with the new structure for maintaining a Deployment repo & source Repo introduced with [1] and [2].

[1]. https://github.com/wso2/carbon-apimgt/pull/9507
[2]. https://github.com/wso2/product-apim-tooling/pull/553

The process of defining certificates using env params file has to recheck and chane according to the latest changes with the recent introduction of Deployment repo directory.

**Suggested Labels:**
Type/Docs
Next Release - 4.x

**Suggested Assignees:**

**Related Issues:**
https://github.com/wso2/product-apim-tooling/issues/545

**Comment by wasuradananjith** [comment]
The point "Check the images in **Building a Jenkins CI/CD Pipeline for Dev First Approach** and do the file structure changes (noticed that there are images with the old folder structure [5] and [6]) if applicable." in [1] should be addressed when doing the doc changes here.

[1] https://github.com/wso2/product-apim-tooling/issues/544
