### ISSUE TITLE
[Docs] Revamping the documentation with MI integration

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#556]
**Description:**
Since we are integrating MI with APICTL with [1], we need to change the documentation where necessary.

**Suggested Labels:**
Type/Docs
Next Release - 4.x 

**Affected Product Version:**
APICTL 4.x

[1] https://github.com/wso2/product-apim-tooling/pull/549

**Comment by npamudika** [comment]
Add a separate section named "**Managing Integration with CTL**" and add sub pages based on the use cases/commands.

**Comment by SanojPunchihewa** [comment]
Need to update the docs with the commands introduced by the following PRs,

#550 - Update commands to add MI instances
#566 - Add commands to retrieve details about artifacts deployed in MI instances
#570 - Add commands to add, update and delete users and loggers in MI instances
#573 - Add commands to activate and deactivate endpoints, message processors, and proxy services in MI instances
#576 - Add commands to encrypt secrets

**Comment by wasuradananjith** [comment]
This can be closed since the revamping has been done with the above referenced PRs.
