### ISSUE TITLE
[Docs] Introduce new features and improvements which were done to APICTL in "About this Release" section

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#558]
**Description:**
With the new features and improvements that were done via APICTL, we need to add the notes on those in the "About this Release" section [1] as a summary.

Currently below features/improvements have been identified.
1. Merge Micro-Integrator CLI commands with APICTL
2. Introducing Alias for APICTL commands and deprecating some of the old commands (need to provide a list)
3. Create a structure for Deployment repo & source Repo
4. Defining schemas for API Controller API/API Product/Application project artifacts (A part of migrating data via apictl)
5. Adding proxy environment variables support for APICTL

Please add the other features/improvements which should be mentioned in the "About this Release" section, as comments to the same issue.

**Suggested Labels:**
Type/Docs
Next Release - 4.x 
Priority/Normal

[1] https://apim.docs.wso2.com/en/next/get-started/about-this-release/

**Comment by Chamindu36** [comment]
We need to add the list of previous apictl commands which were depreciated, in this section.

https://github.com/wso2/docs-apim/pull/2441#discussion_r539394399

**Comment by wasuradananjith** [comment]
The doc links on **apictl aws init** and modified vcs functionality is still not available. Those should be added to the About this Release section of APICTL once finalized. Hence, reopening the issue.

**Comment by wasuradananjith** [comment]
This has been completed via [1] and [2].

[1] https://github.com/wso2/docs-apim/pull/3661
[2] https://github.com/wso2/docs-apim/pull/3826
