### ISSUE TITLE
Support allowed subscription tiers as environment specific parameters

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#564]
**Description:**
Allowed tiers for APIs (when subscribing from Store) can only be provided via api.yaml.
The requirement is came from a customer where they need to allow lower tiers (eg Bronze) in lower environments and higher tiers in higher environments (TEST and PROD)

**Affected Product Version:**
2.6.0 to 3.2.0

**Comment by npamudika** [comment]
Fixed in the APIMCLI 2.0.12 release - https://github.com/wso2/product-apim-tooling/releases/tag/v2.0.12
