### ISSUE TITLE
Provide ability to change the TLS renegotiation mode of the apimcli tool

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim-tooling#577]
**Description:**
Needs to implement a feature that allows the capability to change the TLS renegotiation mode of the connection from the apimcli tool to the external party (eg: Loadbalancer, APIM server, etc) .

Note that Golang disables TLS renegotiation out of the box.

**Affected Product Version:**

2.0.8 Linux version

**Comment by npamudika** [comment]
The fix will be available in the APIMCLI 2.0.13 patch release and the APICTL 4.0.0 major release.
