### ISSUE TITLE
Need integration tests for REST APIs that have been used for import/export tasks

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#597]
**Description:**
Currently, we do not have integration tests for the newly revamped REST APIs in [1] - [3]. There is a need to write some integration tests to check the basic import/export functionality in product-apim.
Further, we need to check whether there is a need to write other integrations tests such as for listing, change-status etc on product-apim side.

**Suggested Labels:**
4.0.0 
Priority/Highest 
Type/Task

**Affected Product Version:**
APIM 4.0.0
APICTL 4.0.0

[1] https://github.com/wso2/carbon-apimgt/pull/9406
[2] https://github.com/wso2/carbon-apimgt/pull/9464
[3] https://github.com/wso2/carbon-apimgt/pull/9533

**Comment by uvindra** [comment]
Current tests have been done for following scenarios at product-apim level,

1. Exporting API and Importing API
2. Updating imported API
3. Invoke imported API
4. Preserve provider of imported API
5. Do not preserve provider of imported API

**Comment by wasuradananjith** [comment]
As per the internal discussion we thought of closing this issue since the number of integration tests residing in the product-apim repository is enough and we maintain more integration tests written in Go lang in this repository.
