### ISSUE TITLE
Need to add missing integration tests to CTL side

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#600]
**Description:**
We need to write integration tests for some scenarios such as below which have been missed currently.
1. Export/Import SOAP API (and invoke API)
2. Export/Import SOAP to REST API (and invoke API)
3. Export/Import GraphQL API (and invoke API)
4. Export/Import GraphQL API and check whether the complexity related data has been exported/imported (and invoke API)
5. Export/Import WebSocket API (and invoke API)

IMO, it is enough if we can have these tests only for Internal/devops users.
Hint: When writing the above tests we might need to generate keys as well so that those keys can be used to invoke the API.

If you find any more tests to be added, feel free to comment on this issue.

**Suggested Labels:**
4.0.0

**Comment by wasuradananjith** [comment]
The tests related to **apictl gen deployment-dir** and API/API Product params were added via https://github.com/wso2/product-apim-tooling/pull/657

**Comment by Chamindu36** [comment]
Integration tests were added with the following PRs.

- https://github.com/wso2/product-apim-tooling/pull/725
- https://github.com/wso2/product-apim-tooling/pull/719
- https://github.com/wso2/product-apim-tooling/pull/722
- https://github.com/wso2/product-apim-tooling/pull/728
- https://github.com/wso2/product-apim-tooling/pull/729
- https://github.com/wso2/product-apim-tooling/pull/730
- https://github.com/wso2/product-apim-tooling/pull/732
- https://github.com/wso2/product-apim-tooling/pull/735
- https://github.com/wso2/product-apim-tooling/pull/736
