### ISSUE TITLE
Add revision support to CTL

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim-tooling#601]
**Description:**
Due to the new revision feature (https://github.com/wso2/product-apim/issues/9406) in APIM 4.0.0, previous flows in apim import export will not work straight forward. Previously, when exporting the artifact, it contained all the deployment environments and once reimport it, the deployment will work as it is. However with new revisioning support, the export will export only the working copy without the environments and once this is imported, only the api will be displayed in the devportal, but not deployed in the respective gateways.

We have to 

1.  Export the deployment environments when exporting.
2. Create a new revision and deploy them in respective environments when importing.
3. Add support to list revisions per api.
4. Add support to deploy and undeploy revisions from ctl.

**Affected Product Version:**
APICTL 4.0.0

**Comment by wasuradananjith** [comment]
This can be closed since the base functionality and the main flow has been completed via the above-referenced PRs.
