### ISSUE TITLE
Update apiclt mg commands after renaming microgateway

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim-tooling#685]
**Description:**
Recently microgateway has been renamed to a different name. So the commands starting `apictl mg` would not be suitable any more. We need to fix this before 4.0.0-GA

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by wasuradananjith** [comment]
As per the discussions with @Rajith90  this can be closed since we have decided to keep the name as it is in apictl side.
