### ISSUE TITLE
Wrong file structure when exporting an Application belongs to a user from a secondary user store

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#717]
**Description:**
When you export an application to a user that belongs to a secondary user store (example; IS/admin) the exported application structure will be incorrect. Refer the below structure which is wrong.
```
IS#admin_TestApp
└── IS
    ├── admin-TestApp
    │   └── application.yaml
    └── application_meta.yaml
```

The correct structure should be like below.
```
IS#admin_TestApp
├── application.yaml
└── application_meta.yaml
```

**[IS#admin_TestApp.zip](https://github.com/wso2/product-apim-tooling/files/6363101/IS.admin_TestApp.zip)** : Refer to this attached .zip file which contains an actual exported application from a secondary user store.

**Affected Product Version:**
APICTL 4.0.0-RC1
APIM 4.0.0-RC1

**Steps to reproduce:**
1. Export an application using a user in a secondary user store.
2. The folder structure will be as follows which is wrong.
```
IS#admin_TestApp
└── IS
    ├── admin-TestApp
    │   └── application.yaml
    └── application_meta.yaml
```

**Comment by uvindra** [comment]
Should implement same fix done for https://github.com/wso2/product-apim-tooling/issues/113 on APIM server side
