### ISSUE TITLE
Properties are not updated for Production/Sandbox keys of an Application when importing with apictl

### ISSUE THREAD

**Issue by ragwap** [wso2/product-apim-tooling#738]
**Description:**

Properties such as expiry times, grant types etc under Product/Sandbox keys in an application are set to default values when exporting with WSO2 API Controller v3.2.1.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO2 APIM 3.2.0 (1619878562980)

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

- Once an application is created in devportal, we can edit expiry times, grant types and etc under both Production and Sandbox keys. 
- After changing expiry times under production keys, I exported the application with apictl and deleted the application from the devportal.
- Exported json had the updated expiry time values.
- Then again I imported the application which was previously exported. 
- It was observed that, even though the values I changed for expiry times are correctly exported in the json, those values are being set to the default values (in the devportal) once imported.

**Related Issues:**

**Comment by npamudika** [comment]
This needs to be fixed in the APIM side and the fixes will be available in a next WUM updated APIM 3.2.0 pack.

**Comment by npamudika** [comment]
This will be available in the latest WUM updated APIM 3.2.0 pack
