### ISSUE TITLE
[2.x] List APIs only shows 25 APIs and other are not displayed.

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim-tooling#757]
**Description:**
When we run a "list apis" command with APIM manager 2.x versions, it shows only the first 25 APIs. If we have more than 25 APIs, there's no way to get all the APIs listed. 

**Affected Product Version:**
APIM Manager 2.0.0 , apimcli-2.0.14-linux-x64.tar.gz

**Steps to reproduce:**
1. Start the APIM server.
2. Log in to the publisher portal.
3. Create 26 apis.
4. Setup apimcli tool.
5. Log in to the apimcli tool environment.
6. Execute list apis command.

**Comment by npamudika** [comment]
Related issues - https://github.com/wso2/product-apim-tooling/issues/265

**Comment by wasuradananjith** [comment]
Related doc issue is in [1]. After PR [2] is merged, the relevant doc changes should be done in the APIM 2.6.0 doc space.

[1] https://github.com/wso2/product-apim-tooling/issues/281
[2] https://github.com/wso2/product-apim-tooling/pull/758
