### ISSUE TITLE
Errors when demoting an API from Publish to Created

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim-tooling#761]
### Description

When demoting an API from Publish stage to Created the following error is encountered.

**Command:** `apictl change-status api -a Demote to Created -n PizzaShackAPI -v 1.0.0 -e dev -k`

**Response:**

Error while changing API Status:  400  
 {"code":400,"message":"Bad Request","description":"Action 'Demote' is not allowed. Allowed actions are [Block, Deploy as a Prototype, Demote to Created, Deprecate, Publish]","moreInfo":"","error":[]}

**Command:** `apictl change-status api -a Demote%20to%20Created -n PizzaShackAPI -v 1.0.0 -e dev -k`

**Response:** PizzaShackAPI API state changed successfully!

From API Controller can't we Encode the request and send it to APIM instead of asking a user to encode the parameters ?

### Affected Product Version:

APICTL 3.2.2

**Comment by wasuradananjith** [comment]
This feature is working on apictl 3.2.1. This must have been broken due to a change in apictl 3.2.2.
![image](https://user-images.githubusercontent.com/25246848/124159635-01447280-dab9-11eb-952c-08d62a6dfa2e.png)
