### ISSUE TITLE
Error in exporting all the APIs of a tenant at once

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim-tooling#762]
### Description:

**Command:** `apictl export-apis -e dev production -k`
**Response :** 
```
Exporting APIs for the migration...
Command: export-apis execution completed !
No APIs available to be exported..!
```

But the APIs are not exported in the `.wso2apictl/exported/migration/dev/tenant-default/apis/` directory.

**Note**  - `./apictl export-apis --environment dev  --format json  --preserveStatus --force -k` command is successfully exporting APIs in the logged in user's tenant.

### Affected versions:

APICTL 3.2.2

**Comment by Chamindu36** [comment]
@Sarangan0219 this is not reproducible in 3.2.2 apictl. And make sure to use the correct command instead of this one. The one that uses has two environments defined in the command. 
`apictl export-apis -e dev`
