### ISSUE TITLE
Request for updated functionality in apictl with --rotate-revision flag

### ISSUE THREAD

**Issue by TharinduNiranjan** [wso2/product-apim-tooling#798]
**Description:**
  Requesting to add --rotate-revision flag into apictl vcs deploy command. Because When we get to 5 revisions and try to run it, it errors out and says we have reached the 5 revision max.

**Suggested Labels:**
apictl, apim4.0.0, type/Improvement

**Affected Product Version:**
WSO2 apictl, APIM 4.0.0

**Comment by npamudika** [comment]
Fixed in APICTL 4.0.1 Release and the releases from APICTL 4.1.0.
