### ISSUE TITLE
APICTL 3.2.3 Batch export feature not working

### ISSUE THREAD

**Issue by inuri2000** [wso2/product-apim-tooling#850]
**Description:**
Export all the API's of a tenant at once feature (batch export) is not working in the latest APIM 3.2.0 update levels. Returns "No apis to be exported " even when there are api's available in the environment.

**Affected Product Version:**
APIM -3.2.0 
APICTL - 3.2.3

**Steps to reproduce:**

run apictl tool and create an environment (prod)
log into the environment (logged in as admin)
list all the apis with command : ./apictl list apis -e prod
execute the export-apis command : ./apictl export-apis -e prod -k --verbose

**Comment by npamudika** [comment]
This is fixed in the 3.2.5 patch release and the releases from APICTL 4.1.0
