### ISSUE TITLE
Add role support to micro-integrator

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-apim-tooling#881]
**Description:**
Introduce add/remove/assign role support to APICTL

**Suggested Labels:**
improvement

**Related Issues:**
wso2/micro-integrator/issues/2571

**Comment by GDLMadushanka** [comment]
Fixed with https://github.com/wso2/product-apim-tooling/pull/876

**Comment by wasuradananjith** [comment]
This is fixed in APIM 4.0.x via https://github.com/wso2/product-apim-tooling/pull/880 and is released with apictl 4.0.2
