### ISSUE TITLE
[APIM CLI] [v3.0.0-alpha]Show proper error message for apimcli k8s mode

### ISSUE THREAD

**Issue by dinusha92** [wso2/product-apim-tooling#96]
**Description:**

When APIMCLI mode is set to k8s and if kubectl related commands are being called, when an error occurs, it doesn't show the proper error message throwing from the kubectl.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by renuka-fernando** [comment]
#### Sample:
Run a command that not supported by kubectl with kubernetes mode of apictl.
```
$ apictl read pods

Error: unknown command "read" for "kubectl"
Run 'kubectl --help' for usage.
apictl: Error executing kubernetes commands  Reason: exit status 1
Exit status 1
```

**Comment by wasuradananjith** [comment]
Since we have deprecated the command flag **--mode** in **apictl set** in apictl 4.0.0, this issue will not be there. Hence, closing this issue.
